apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: dev
  labels:
    app: java
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: javapods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels:
        app: javapods
    spec:
      containers:
        - name: myjava-container
          image: longflew/javarepo
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20  
          resources:
            requests: 
              cpu: 125m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
      
         

    
        
