apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mydemoapp
  namespace: prod
spec:
  containers:
    - name: my-co
      image: nginx:1.29
      ports:
        - containerPort: 80

   
      