apiVersion: v1
kind: Pod
metadata:
  name: static-pod       
spec:
  containers:
    - name: myfirst-container
      image: nginx:1.25
      ports:
        - containerPort: 80   
          protocol: TCP
